/** This package's name, as it appears in orc's log and trace records. */
export const PACKAGE = "@orc/sdk";

export {
  canonical,
  ConfigError,
  defineConfig,
  hash,
  role,
  type ConfigInput,
  type FrozenConfig,
  type ResolvedConfig,
  type ResolvedRole,
  type RoleInput,
} from "./config.js";

export {
  assertId,
  createRun,
  decodeId,
  defaultRunsDir,
  encodeId,
  ID_PATTERN,
  latestRun,
  listRuns,
  newRunId,
  openRun,
  RECORD_VERSION,
  RUN_ID_PATTERN,
  RunDir,
  RunDirError,
  type AgentAsk,
  type AgentInit,
  type AgentPaths,
  type AgentRecord,
  type AgentStatus,
  type ConfigInit,
  type ConfigRecord,
  type CreateRunOptions,
  type ErrorRecord,
  type EscalationAnswer,
  type EscalationInit,
  type EscalationRecord,
  type HashInputs,
  type LogRecord,
  type RunInit,
  type RunRecord,
  type RunReport,
  type RunStatus,
  type RunSummary,
  type StepInit,
  type StepRecord,
  type Usage,
  type VerifyInit,
  type VerifyRecord,
  type WireRecord,
} from "./rundir.js";
